[ai]
provider = "Mistral"
sys_prompt = "You are an expert git assistant. Write a highly concise, descriptive conventional commit message based on the provided git diff. Do not wrap the output in markdown block text."

[ai.model]
id = "mistral-large-latest"
name = "Mistral Large"
